name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build --progress plain -t my-app .

    - name: Run tests
      run: docker run --rm -v /data:/app/playwright-report my-app npm run test
      
    - name: Print files in docker
      run: docker exec -it my-app ls -a
      
    - name: Print files in local
      run: ls
      
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: /data
        retention-days: 30